#!/bin/bash

# Variable explanations
# input: connector type they NEED for src
# in_gender: connector gender they NEED for src
# output: connector type they NEED for dest
# out_gender: connector gender they NEED for dest

# Usage information if they didn't enter correct arguments
if [ $# -lt 4 ]
    then
        printf "Usage: $0 input output in_gender out_gender\n"
        printf "\nList of possible connections:\n"
        printf "VGA\nDVI\nDP\nHDMI\n" #dont forget mini
	exit 1
fi

printf "Welcome to the adapter finder.\n"

# lowercase input and output
input=${1,,}
output=${2,,}
in_gender=${3,,}
out_gender=${4,,} #get first letter only
# passive?
# different DVI connections?

printf "You selected to go from ${input^^} ($in_gender) -> ${output^^} ($out_gender)\n"

### FIND DIRECT CONNECTION ###

# for finding matching row
input_gender=$input+$in_gender

file="./adapters_avail"
while IFS=',' read -r name gender vga dvi dp hdmi
do
    # find row with the same connector type
    name_gender=$name+$gender
    if [ "$input_gender" = "$name_gender" ]
        then
            # find column for desired connector
            eval avail_out=\$$output
            f_count="$(cut -d':' -f1 <<< "$avail_out")"
            m_count="$(cut -d':' -f2 <<< "$avail_out")"
            printf "$f_count $m_count\n"
    fi
    if [ $avail_count -eq 0 ] # no direct connection
        then
            printf "There are no direct connections."
            ### CHECK OUTPUT ###

            break
    fi
done < "$file"
